In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [3]:
# Creating a NumPy Array

lst=[1.5]

arr=np.array(lst)
print(arr)

[1.5]


In [4]:
# .dtype attribute
print(arr.dtype)

float64


In [5]:
"""
Size Comparison of ndarray and lust objects
"""

from sys import getsizeof

lst=[1,2,3,4,5]
print(getsizeof(lst))

arr=np.array(lst)
print(getsizeof(arr))

96
124


In [6]:
"""
Operations with Numpy Arrays
"""

prices=[30,25,40,20,20,35,50,35]

# With a list
new_prices=[price-5 for price in prices]
print(new_prices)

# With a ndarray
prices_arr=np.array(prices)
prices_arr=prices_arr - 5
print(prices_arr)

# ** operation and np.sqrt



[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [7]:
"""
Exercise: Test Scores
"""

test_1=np.array([92,94,88,91,87])
test_2=np.array([79,100,86,93,91])
test_3=np.array([87,85,72,90,92])

test_3_fixed=test_3+2
print(test_3_fixed)

total_grade=test_1+test_2+test_3
print(total_grade)

final_grade=total_grade/3
print(final_grade)

jeremy_test_2=test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1=np.array([test_1[1],test_1[2]])
print(manual_adwoa_test_1)

student_scores=np.array([test_1,test_2,test_3])
print(student_scores)

print(student_scores[2,0])

print(student_scores[:,-1])

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [8]:
"""
Logical Operations with Arrays
"""

# masking

a=np.array([10,2,2,4,5,3,9,8,9,7])
mask=a>5
print(mask)

# select using Logical operations

selected=a[(a>6)|(a<4)]
print(selected)

# combined Logical oprations | &

selected=a[(a>4)&(a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  2  2  3  9  8  9  7]
[5 7]


In [9]:
students_scores=np.array([test_1,test_2,test_3])

print(students_scores)

print(students_scores[2,0])

print(students_scores[:,-1])

[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [10]:
"""
Logical Operations with Arrays
"""

#masking
a=np.array([10,2,2,4,5,3,9,8,9,7])

mask=a>5
print(mask)

#select using logical operations
selected=a[a>5]
print(selected)

#combined Logical operations/&
selected=a[(a>6)|(a<4)]
print(selected)

selected=a[(a>4)&(a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [17]:
porridge=np.array([79,65,50,63,56,90,85,98,79,51])

cold=porridge[porridge<60]
print(cold)

hot=porridge[porridge<60]
print(hot)

just_right=porridge[(porridge<80)&(porridge>60)]
print(just_right)

[50 56 51]
[50 56 51]
[79 65 63 79]
